services:
  vue-dashboard:
    build:
      dockerfile: ./dockerfiles/node/frontend.prod.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./vue-dashboard:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - app

  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./src:/var/www
      - ./dockerfiles/nginx/conf.d/backend.prod.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - app
      - db
      - redis
    networks:
      - app-network
      - proxy

  app:
    build:
      dockerfile: ./dockerfiles/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USER: ${USER:-www}
    image: vue-material-dashboard-laravel-app
    container_name: vue-material-dashboard-laravel_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www:delegated
      - ./dockerfiles/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ../shared/storage:/var/www/storage:delegated
      - ../shared/.env:/var/www/.env
    networks:
      - app-network

  db:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-homestead}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      SERVICE_TAGS: ${SERVICE_TAGS:-dev}
      SERVICE_NAME: ${SERVICE_NAME:-db}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
      - ./dockerfiles/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
      - ./dockerfiles/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    command: redis-server --requirepass ${REDIS_PASSWORD}

  supervisor:
    image: vue-material-dashboard-laravel-app
    depends_on:
      - web
      - app
    volumes:
      - ./src:/var/www:delegated
      - ../shared/storage:/var/www/storage:delegated
      - ../shared/.env:/var/www/.env
    networks:
      - app-network
    command: supervisord -c /etc/supervisor/conf.d/laravel-json-api.conf

networks:
  proxy:
    name: nginx-proxy
    external: true
  app-network:
    name: vue-material-dashboard-laravel_network
    driver: bridge

volumes:
  dbdata:
    name: vue-material-dashboard-laravel_dbdata
    driver: local
  redis:
    name: vue-material-dashboard-laravel_redis
    driver: "local"
